repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uvx black .
        language: system
        types: [ python ]

      - id: ruff
        name: ruff
        entry: uvx ruff check --fix .
        language: system
        types: [ python ]
